version: 1.0.{build}
build_script:
- cmd: >-
    dotnet restore

    dotnet build **/project.json
test_script:
- cmd: >-
    cd test\vatCalc.test
    
    dotnet test -xml ..\..\result.xml

    cd ..\..\
after_test:
- ps: >-
    $wc = New-Object 'System.Net.WebClient'

    $wc.UploadFile("https://ci.appveyor.com/api/testresults/xunit/$($env:APPVEYOR_JOB_ID)", (Resolve-Path .\results.xml))